/**
 * Deterministic agent runner.
 *
 * Every model interaction in DesignLab is schema-shaped, which means a runner
 * that synthesises schema-valid answers can drive the *entire* pipeline —
 * worktree creation, real builder file edits, real gate commands, real
 * protection diffs, real lineage — without a single token being spent.
 *
 * This backs both `--dry-run` and the integration tests, so the tests exercise
 * the production orchestrator rather than a parallel fake of it.
 */

import { writeFile, mkdir, readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

import type { z } from 'zod';

import { DIVERSITY_DIMENSIONS } from '../core/schemas.js';
import type { AgentRequest, AgentResponse, AgentRole, AgentRunner } from './types.js';

export interface MockRunnerOptions {
  models?: Partial<Record<AgentRole, string>>;
  /**
   * When true, builder invocations write a real marker file into the
   * worktree so downstream gates see an actual diff. Disable for pure
   * planning tests.
   */
  applyBuilderEdits?: boolean;
  /** Force specific operations to fail, keyed by operation name. */
  failOperations?: ReadonlySet<string>;
  /** Observed requests, for assertions. */
  calls?: AgentRequest[];
}

const DEFAULT_MODELS: Record<AgentRole, string> = {
  lead: 'mock-lead',
  builder: 'mock-builder',
  reviewer: 'mock-reviewer',
};

export class MockAgentRunner implements AgentRunner {
  readonly name = 'mock';
  readonly calls: AgentRequest[];

  private readonly models: Record<AgentRole, string>;
  private readonly applyBuilderEdits: boolean;
  private readonly failOperations: ReadonlySet<string>;

  constructor(options: MockRunnerOptions = {}) {
    this.models = { ...DEFAULT_MODELS, ...options.models };
    this.applyBuilderEdits = options.applyBuilderEdits ?? true;
    this.failOperations = options.failOperations ?? new Set();
    this.calls = options.calls ?? [];
  }

  modelFor(role: AgentRole): string {
    return this.models[role];
  }

  isAvailable(): Promise<boolean> {
    return Promise.resolve(true);
  }

  async run<TSchema extends z.ZodTypeAny>(
    request: AgentRequest<TSchema>,
  ): Promise<AgentResponse<z.infer<TSchema>>> {
    this.calls.push(request as AgentRequest);
    const model = this.modelFor(request.role);

    if (this.failOperations.has(request.operation)) {
      return {
        ok: false,
        role: request.role,
        model,
        operation: request.operation,
        text: '',
        data: null,
        usage: { costUsd: 0, inputTokens: 0, outputTokens: 0, numTurns: 0 },
        durationMs: 1,
        error: `mock runner was configured to fail operation "${request.operation}"`,
        sessionId: null,
      };
    }

    if (request.role === 'builder' && this.applyBuilderEdits) {
      await this.applyDesignEdit(request);
    }

    const data = request.outputSchema
      ? (synthesise(request) as z.infer<TSchema>)
      : null;

    return {
      ok: true,
      role: request.role,
      model,
      operation: request.operation,
      text: data ? JSON.stringify(data) : `mock ${request.role} completed ${request.operation}`,
      data,
      usage: { costUsd: 0, inputTokens: 0, outputTokens: 0, numTurns: 1 },
      durationMs: 1,
      error: null,
      sessionId: `mock-${request.operation}`,
    };
  }

  /**
   * Writes a plausible, design-only change into the worktree. It touches a
   * theme file (DESIGNABLE by every rule set) so that the protection gate has
   * genuine content to evaluate rather than an empty diff.
   */
  private async applyDesignEdit(request: AgentRequest): Promise<void> {
    const slot = request.ledger?.slot ?? 'x';
    const marker = join(request.cwd, 'src', 'theme', `designlab-${String(slot).toLowerCase()}.ts`);
    await mkdir(dirname(marker), { recursive: true });
    await writeFile(
      marker,
      [
        `// Generated by the DesignLab mock builder for slot ${slot}.`,
        '// Presentation-only: no business logic, no protected surface.',
        'export const designTokens = {',
        `  variant: ${JSON.stringify(String(slot).toLowerCase())},`,
        "  spacingScale: [4, 8, 12, 16, 24, 32],",
        "  radius: 16,",
        '};',
        '',
      ].join('\n'),
      'utf8',
    );

    // Also nudge an existing theme file when one is present, so the diff
    // resembles a real redesign rather than a pure file addition.
    const themeCandidates = ['src/theme/theme.ts', 'src/theme.ts', 'lib/theme.dart', 'app/theme.ts'];
    for (const candidate of themeCandidates) {
      const path = join(request.cwd, candidate);
      try {
        const existing = await readFile(path, 'utf8');
        await writeFile(path, `${existing}\n// designlab variant: ${String(slot).toLowerCase()}\n`, 'utf8');
        break;
      } catch {
        // Not present; try the next candidate.
      }
    }
  }
}

/**
 * Produces a schema-valid object for any of DesignLab's structured requests.
 * Keyed on operation so each stage receives a shape that makes downstream
 * assertions meaningful (distinct slugs, differing diversity vectors, etc).
 */
function synthesise(request: AgentRequest): unknown {
  const count = extractRequestedCount(request.prompt);

  switch (request.operation) {
    case 'plan-round':
      return {
        strategy:
          'Mock strategy: explore four structurally distinct interaction models across the primary flows.',
        designs: Array.from({ length: count }, (_, index) => mockDesign(index)),
      };

    case 'classify-contract':
      return {
        rules: [
          { pattern: 'src/api/**', level: 'PROTECTED', reason: 'Network contracts with the backend.' },
          { pattern: 'src/auth/**', level: 'PROTECTED', reason: 'Authentication behaviour must not change.' },
          { pattern: 'src/theme/**', level: 'DESIGNABLE', reason: 'Visual tokens are the point of the exercise.' },
          { pattern: 'src/screens/**', level: 'DESIGNABLE', reason: 'Screen presentation is designable.' },
        ],
        invariants: [
          {
            id: 'auth-required',
            statement: 'Unauthenticated users must never reach authenticated screens.',
            category: 'authentication',
          },
        ],
        notes: ['Generated by the mock runner.'],
      };

    case 'interpret-reference': {
      const diversityVector = Object.fromEntries(
        DIVERSITY_DIMENSIONS.map((dimension) => [dimension, `reference-${dimension}-position`]),
      );
      return {
        slug: 'reference',
        name: 'Reference',
        thesis: 'Implementation of the supplied reference mockups.',
        rationale: 'Interpreted deterministically by the mock runner.',
        diversityVector,
        directives: [
          'Recreate the composition shown in the reference mockups.',
          'Match the reference typography and spacing scale.',
          'Match the reference component treatment across the target screens.',
        ],
        targetScreens: ['Home'],
        antiPatterns: [],
        successCriteria: ['Screens visually match the supplied mockups.'],
        uncertainties: ['The mockups do not show error or empty states; existing behaviour is kept.'],
      };
    }

    case 'judge-diversity':
      return { verdict: 'distinct', collidingPairs: [], guidance: '' };

    case 'enrich-manifest':
      return {
        navigationPattern: 'stack + bottom tabs',
        stateManagement: ['react-context'],
        notes: ['Mock enrichment: deterministic analysis only.'],
      };

    case 'implement-design':
    case 'revise-design':
      return {
        implemented: true,
        summary: 'Mock builder applied presentation-only changes for the assigned brief.',
        filesChanged: [`src/theme/designlab-${String(request.ledger?.slot ?? 'x').toLowerCase()}.ts`],
        screensTouched: ['Home'],
        deviations: [],
        selfCheck: 'No protected paths touched; changes are presentation-only.',
        blockers: [],
      };

    case 'review-design':
      return {
        briefAdherence: 8,
        distinctiveness: 8,
        internalConsistency: 8,
        functionalityPreservation: 9,
        usability: 8,
        completeness: 7,
        regressionRisk: 2,
        verdict: 'accept',
        summary: 'Mock review: the implementation matches the brief and preserves functionality.',
        corrections: [],
      };

    case 'escalate-failure':
      return {
        diagnosis: 'Mock escalation: the failure is a missing import in the redesigned screen.',
        rootCause: 'Component was renamed without updating its consumers.',
        recoverable: true,
        instructions: ['Update the import path in the affected screen and re-run typecheck.'],
        suspectPaths: [],
        riskNotes: '',
      };

    case 'plan-next-generation':
      return {
        reasoning:
          'Mock evolution plan: keep the winning structure, graft the strongest ideas from rejected siblings, and probe one radical alternative.',
        directions: [
          {
            slug: 'winner-refined',
            name: 'Winner, refined',
            thesis: 'Tighten the winning direction without changing its structure.',
            relation: 'conservative refinement of the winner',
            borrowsFrom: [],
            riskLevel: 'conservative',
          },
          {
            slug: 'winner-plus-map',
            name: 'Winner + rival map',
            thesis: 'Keep the winner but adopt the rival map treatment.',
            relation: 'winner plus a borrowed subsystem',
            borrowsFrom: ['A'],
            riskLevel: 'moderate',
          },
          {
            slug: 'radical-shift',
            name: 'Radical shift',
            thesis: 'Push the winning thesis to its structural extreme.',
            relation: 'radical evolution of the winner',
            borrowsFrom: [],
            riskLevel: 'radical',
          },
        ],
      };

    default:
      return {};
  }
}

const MOCK_DESIGNS = [
  { slug: 'immersive', name: 'Immersive', thesis: 'Content fills the screen; chrome recedes until needed.' },
  { slug: 'social', name: 'Social', thesis: 'People and activity lead; the feed is the product.' },
  { slug: 'premium', name: 'Premium', thesis: 'Calm, generous spacing and restrained typography signal quality.' },
  { slug: 'utility', name: 'Utility', thesis: 'Maximum information density and the shortest path to any action.' },
  { slug: 'spatial', name: 'Spatial', thesis: 'Position and proximity carry the information hierarchy.' },
  { slug: 'editorial', name: 'Editorial', thesis: 'Typographic rhythm structures the entire experience.' },
  { slug: 'kinetic', name: 'Kinetic', thesis: 'Motion explains state; transitions carry meaning.' },
  { slug: 'minimal', name: 'Minimal', thesis: 'One decision per screen; everything else is progressive disclosure.' },
] as const;

function mockDesign(index: number): unknown {
  const base = MOCK_DESIGNS[index % MOCK_DESIGNS.length] ?? MOCK_DESIGNS[0];
  const diversityVector = Object.fromEntries(
    DIVERSITY_DIMENSIONS.map((dimension, dimensionIndex) => [
      dimension,
      `${base.slug}-${dimension}-${(index + dimensionIndex) % 5}`,
    ]),
  );

  return {
    slug: base.slug,
    name: base.name,
    thesis: base.thesis,
    rationale: `Mock rationale for the ${base.name} direction.`,
    diversityVector,
    directives: [
      `Adopt the ${base.name} visual language across all primary screens.`,
      'Restructure the primary navigation presentation to match the thesis.',
      'Rework spacing, typography and component shape as one coherent system.',
    ],
    targetScreens: ['Home'],
    antiPatterns: ['Do not simply recolour the existing layout.'],
    successCriteria: [`A reviewer can identify this as the ${base.name} direction at a glance.`],
    parentRelation: '',
  };
}

/** Reads "produce N designs" out of the prompt so mocks match the request. */
function extractRequestedCount(prompt: string): number {
  const match = /produce\s+(?:exactly\s+)?(\d+)\s+design/i.exec(prompt) ?? /(\d+)\s+distinct design/i.exec(prompt);
  const parsed = match?.[1] ? Number.parseInt(match[1], 10) : 4;
  return Number.isInteger(parsed) && parsed >= 1 && parsed <= 8 ? parsed : 4;
}
